TOP=../..

# R3.13 Makefile

include $(TOP)/config/CONFIG_APP

# Want local functions non-static? Define DEBUG 
#CFLAGS += -DDEBUG

# Any warning is a bug
CFLAGS += -Werror

# library

LIBNAME = s7plcLib
SRCS += drvS7plc.c
SRCS += devS7plc.c
LIBOBJS = $(SRCS:.c=.o)
DBDINSTALL += s7plc.dbd
HTMLS += s7plc.html

include $(TOP)/config/RULES.Vx

s7plc.dbd: ../s7plcBase.dbd
	$(CP) $^ $@
