TOP=../..
include $(TOP)/configure/CONFIG

LIBRARY = s7plc

DBD += s7plc.dbd
LIB_SRCS += s7plc_registerRecordDeviceDriver.cpp

HOST_OPT = NO
CFLAGS += -DDEBUG -Werror

LIB_SRCS += tiCP.c
LIB_SRCS += drvS7plc.c
LIB_SRCS += devS7plc.c
#LIB_SRCS += devS7memStat.c

LIB_LIBS += Com
LIB_LIBS += dbIoc
LIB_LIBS += dbStaticIoc
LIB_LIBS += iocsh
LIB_LIBS += registryIoc

PROD = s7plcApp
DBD += s7plcApp.dbd

s7plcApp_DBD += base.dbd
s7plcApp_DBD += s7plc.dbd

s7plcApp_SRCS += s7plcApp_registerRecordDeviceDriver.cpp
s7plcApp_SRCS_DEFAULT += appMain.cc
s7plcApp_SRCS_vxWorks += -nil-

s7plcApp_LIBS += s7plc
s7plcApp_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES
